groups:
  - name: reactive-api
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 30 seconds."

      - alert: HighErrorRate
        expr: (sum(rate(vertx_http_server_response_time_seconds_count{code=~"5.."}[1m])) by (job) / sum(rate(vertx_http_server_response_time_seconds_count[1m])) by (job)) * 100 > 5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High Error Rate detected"
          description: "Instance {{ $labels.instance }} error rate is above 5% (current value: {{ $value }}%)"

      - alert: HighLatency
        expr: histogram_quantile(0.95, sum(rate(vertx_http_server_response_time_seconds_bucket[5m])) by (le)) > 0.5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High Latency detected"
          description: "P95 Latency is above 500ms (current value: {{ $value }}s)"
